# Generated by Django 2.0 on 2018-08-16 23:25

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('url', models.CharField(max_length=500, unique=True)),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('access_count', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='savedlink',
            name='url',
            field=models.ForeignKey(on_delete='CASCADE', to='URLshortener.URL'),
        ),
        migrations.AddField(
            model_name='savedlink',
            name='user',
            field=models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
