# Generated by Django 2.0 on 2018-08-17 20:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('URLshortener', '0002_auto_20180816_1631'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedLink',
            new_name='UserSavedLink',
        ),
    ]
